//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 2014-05-16 오후 2:23:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using NHibernate.Classic;
using System.Runtime.Serialization;

namespace HubCrawl.Data
{

    /// <summary>
    /// There are no comments for HubCrawl.Data.Gender, HubCrawl.Data in the schema.
    /// </summary>
    [DataContract()]
    public enum Gender : int
 {
    
        /// <summary>
        /// There are no comments for Gender.Male in the schema.
        /// </summary>
        [EnumMember]
        Male = 1,    
        /// <summary>
        /// There are no comments for Gender.Female in the schema.
        /// </summary>
        [EnumMember]
        Female = 2
    }

}
